spring.application.name=springboot-distributed-system-demo

spring.profiles.active=${SPRING_ACTIVE_PROFILE:local}

spring.mongodb.uri=${MONGODB_CONNECTION_URL}

spring.data.redis.host=localhost
spring.data.redis.port=6379
