spring.application.name=springboot-distributed-system-demo

spring.profiles.active=${SPRING_ACTIVE_PROFILE:local}

spring.mongodb.database=${MONGODB_NAME}
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.username=${MONGODB_USERNAME}
spring.mongodb.password=${MONGODB_PASSWORD}
